name: check-description
description: GitHub Action for check description of pull request
author: Kirill Vedmetskii

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  mode:
    description: The mode of action. May be 'strict', 'draft' and 'comment'
    required: true
    default: 'comment'

runs:
  using: node24
  main: dist/index.js
